pdf:
  image: sphinxdoc/sphinx-latexpdf
  script:
  - make latex
  - cd build/latex/
  - sed -e 's/chapter{Preface}/chapter*{Preface}/' -i thesecurityanalystsguidetosuricata.tex
  - make
  - cd ../..
  - make epub
  artifacts:
    expire_in: 2 week
    paths:
      - "build/latex/*pdf"
      - "build/epub/*epub"

print:
  image: sphinxdoc/sphinx-latexpdf
  script:
  - sed -e 's/   license//' -i source/about.rst
  - make latex PRINT=1
  - cd build/latex/
  - sed -e 's/chapter{Preface}/chapter*{Preface}/' -i thesecurityanalystsguidetosuricata.tex
  - make
  - mv thesecurityanalystsguidetosuricata.pdf thesecurityanalystsguidetosuricata-print.pdf
  artifacts:
    expire_in: 2 week
    paths:
      - "build/latex/*-print.pdf"
